services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
    restart: always
 
volumes:
  pgdata:
